# Generated by Django 5.2.1 on 2025-09-13 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(null=True)),
                ('account_name_1', models.TextField(null=True)),
                ('debit_1', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
                ('credit_1', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
                ('account_name_2', models.TextField(null=True)),
                ('debit_2', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
                ('credit_2', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
            ],
            options={
                'db_table': 'sample',
            },
        ),
    ]
