# Generated by Django 5.2.1 on 2025-10-11 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_code', models.TextField(primary_key=True, serialize=False)),
                ('account_name', models.TextField()),
                ('account_type', models.TextField()),
            ],
            options={
                'db_table': 'sample_accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(null=True)),
                ('account_name_1', models.TextField(null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
                ('account_name_2', models.TextField(null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=9, max_digits=18)),
            ],
            options={
                'db_table': 'sample',
            },
        ),
        migrations.CreateModel(
            name='USN_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
            ],
            options={
                'db_table': 'sample_usn_accounts',
            },
        ),
    ]
