# Generated by Django 5.2.1 on 2025-09-13 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='account_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
