# Generated by Django 5.2.1 on 2025-09-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.BigIntegerField()),
                ('account_name', models.TextField(null=True)),
                ('account_type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'sample_accounts',
            },
        ),
    ]
