# Generated by Django 5.2.1 on 2025-09-13 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account_name_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_1',
            field=models.DecimalField(decimal_places=10, blank=True, max_digits=19),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_1',
            field=models.DecimalField(decimal_places=10, blank=True, max_digits=19),
        ),
         migrations.AddField(
            model_name='journalentry',
            name='account_name_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_2',
            field=models.DecimalField(decimal_places=10, blank=True, max_digits=19),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_2',
            field=models.DecimalField(decimal_places=10, blank=True, max_digits=19),
        ),
    ]
