# Generated by Django 5.2.1 on 2025-09-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0002_journalentry_account_name_journalentry_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='account_name',
            new_name='accounts_name',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=30),
        ),
    ]
