# Generated by Django 5.2.1 on 2025-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0002_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='USN_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
            ],
            options={
                'db_table': 'sample_usn_accounts',
            },
        ),
    ]
