# Generated by Django 5.2.1 on 2025-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0003_usn_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
