# Generated by Django 5.2.1 on 2025-09-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0003_rename_account_name_journalentry_accounts_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='accounts_name',
            new_name='account_name',
        ),
    ]
