# Generated by Django 5.2.1 on 2025-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0004_remove_accounts_id_alter_accounts_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit_1',
            field=models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit_2',
            field=models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=18),
        ),
    ]
