# Generated by Django 5.2.1 on 2025-09-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0004_rename_accounts_name_journalentry_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=15),
        ),
    ]
