# Generated by Django 5.2.1 on 2025-09-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0005_alter_journalentry_credit_alter_journalentry_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
