# Generated by Django 5.2.1 on 2025-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0005_alter_journalentry_credit_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
