# Generated by Django 5.2.1 on 2025-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0006_alter_journalentry_credit_alter_journalentry_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18),
        ),
    ]
