# Generated by Django 5.2.1 on 2025-10-11 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0006_alter_accounts_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account_name_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_System.accounts'),
        ),
    ]
