# Generated by Django 5.2.1 on 2025-09-13 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0007_alter_journalentry_credit_alter_journalentry_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
