# Generated by Django 5.2.1 on 2025-10-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0007_alter_accounts_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account_name_1',
            field=models.TextField(null=True),
        ),
    ]
