# Generated by Django 5.2.1 on 2025-09-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0008_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journalentry',
            table='sample1',
        ),
    ]
