# Generated by Django 5.2.1 on 2025-10-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System', '0008_alter_journalentry_account_name_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.TextField(null=True),
        ),
    ]
